### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by mythical123** [drinfernoo/script.extendedinfo#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mythical123** [comment]
Hi you cant link in a skin from movies straight into all movies in the extended info mod same in tv shows. As its in no folder section of the plugin py.

**Comment by drinfernoo** [comment]
Use it as a Video add-on to be able to do this.

**Comment by mythical123** [comment]
That's what I am saying if you do it as a video addon. It doesn't show you the option of all movies or all tv shows. That goes direct into the EIM

**Comment by drinfernoo** [comment]
Are you trying to make a shortcut to it or a widget?

**Comment by drinfernoo** [comment]
In the meantime, you can try to use `RunScript(script.extendedinfo)` for a shortcut to "All Movies", and `RunScript(script.extendedinfo,info=alltvshows)` for "All TV Shows".

**Comment by mythical123** [comment]
Thanks for your response no I am trying to link if you click on the movies
tab it opens the extended info mod. It currently does do that it stop at
all movies?
