### ISSUE TITLE
[Bug]Play button visibility

### ISSUE THREAD

**Issue by JayDigg** [drinfernoo/script.extendedinfo#7]
Sorry, not really a bug. 
So I really like the netflix view with trailers set to autoplay. My only dislike is that the play button is not visible until the trailer is done playing, or you manually hit the stop trailer button. When the trailer is playing the Play button is replaced by a full screen button. Maybe its just my preference, but i think it would be nice to have the Play button always visible and ready to play. IMO it kinda ruins the fluid experience if you have to hit the stop trailer button before you can hit play. Just a thought.
![screenshot_1](https://user-images.githubusercontent.com/45118866/53699071-6df8b680-3db2-11e9-985a-1d5eabb65145.png)

**Comment by drinfernoo** [comment]
This is actually by design, as trying to play *while* the trailer is playing can cause a while bunch of issues. We tested the shit out of it, and could only come up with this as a solution. *Maybe* in the future, but that's a big maybe.

**Comment by JayDigg** [comment]
Ahh, was wondering if that was the case. Makes sense. I would think just adding a command to stop video before the player selection screen opened would prevent any issues, but you probably tried that.
